org: estagiario
service: datacore

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  
provider:
  name: aws
  runtime: nodejs18.x

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
